spring.application.name=StayLanka

# Enable H2 console
spring.h2.console.enabled=true

# (Optional) Customize the path if needed (default is /h2-console)
spring.h2.console.path=/h2-console

# Database configuration (example for an in-memory database)
spring.datasource.url=jdbc:h2:mem:staylanka
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
